"""add_fee_tables_and_columns

Revision ID: a003e76cee47
Revises: df068f5673f3
Create Date: 2026-06-27 19:53:43.406446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a003e76cee47'
down_revision: Union[str, Sequence[str], None] = 'df068f5673f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_rules',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('fee_type', sa.Enum('flat', 'percentage', 'hybrid', name='feetype'), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('percentage_rate', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_rules_name'), 'fee_rules', ['name'], unique=False)
    op.create_table('transaction_fees',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('fee_rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.Enum('flat', 'percentage', 'hybrid', name='feetype'), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('percentage_rate', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('computed_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'waived', 'refunded', name='feestatus'), server_default='pending', nullable=False),
    sa.Column('waived_reason', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['fee_rule_id'], ['fee_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_fees_fee_rule_id'), 'transaction_fees', ['fee_rule_id'], unique=False)
    op.create_index(op.f('ix_transaction_fees_transaction_id'), 'transaction_fees', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_fees_user_id'), 'transaction_fees', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('fee_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_fee_id'), 'transactions', ['fee_id'], unique=False)
    op.create_foreign_key('fk_transactions_fee_id', 'transactions', 'transaction_fees', ['fee_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_fee_id', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_fee_id'), table_name='transactions')
    op.drop_column('transactions', 'fee_id')
    op.drop_index(op.f('ix_transaction_fees_user_id'), table_name='transaction_fees')
    op.drop_index(op.f('ix_transaction_fees_transaction_id'), table_name='transaction_fees')
    op.drop_index(op.f('ix_transaction_fees_fee_rule_id'), table_name='transaction_fees')
    op.drop_table('transaction_fees')
    op.drop_index(op.f('ix_fee_rules_name'), table_name='fee_rules')
    op.drop_table('fee_rules')
    # ### end Alembic commands ###
